swagger: '2.0'
schemes:
  - https
host: diccionario-de-calle.swagger.io
basePath: /v2
info:
  description: 'API layer to access database with Spanish slang'
  version: 1.0.0
  title: Diccionario de Calle
  contact:
    email: maria.losafo@gmail.com
tags:
  - name: country
    description: Access to Spanish-speaking countries info
  - name: entry
    description: Access to dictionary entries
securityDefinitions:
  api_auth:
    type: oauth2
    authorizationUrl: 'https://some-url.com'
    flow: implicit
    scopes:
      'write:calle': add entries to dictionary
      'read:calle': read entries from dictionary
  api_key:
    type: apiKey
    name: api_key
    in: header
paths:
  /:
    get:
      tags:
        - entry
      summary: Get entries
      description: Returns a list of entries
      parameters:
        - name: entryLimit
          in: query
          description: Number of entries to be returned
          required: false
          type: number
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
        '500':
          description: Internal Server Error
      security:
        - api_key: [ ]
    post:
      tags:
        - entry
      summary: Add a new entry
      description: Add a new entry to the dictionary
      parameters:
        - name: body
          in: body
          description: Entry information
          required: true
          schema:
            $ref: "#/definitions/Entry"
      produces:
        - application/json
      responses:
        '201':
          description: successful operation
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      security:
        - api_key: [ ]
  /{id}:
    delete:
      tags:
        - entry
      summary: Remove an entry
      description: Remove one entry by Id
      parameters:
        - name: id
          in: path
          description: Id of the entry
          required: true
          type: number
      produces:
        - application/json
      responses:
        '201':
          description: successful operation
        '500':
          description: Internal Server Error
      security:
        - api_key: [ ]
definitions:
  Entry:
    type: object
    properties:
      term:
        description: "name of the entry"
        type: string
        example: "Dog"
      definition:
        type: string
      countryUse:
        type: array
        items:
          type: string